#![allow(
    dead_code,
    mutable_transmutes,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused_assignments,
    unused_mut
)]
pub(crate) type __uint8_t = libc::c_uchar;
pub(crate) type uint8_t = __uint8_t;
static mut swb_size_128_96: [uint8_t; 12] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
];
static mut swb_size_128_64: [uint8_t; 12] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
];
static mut swb_size_128_48: [uint8_t; 14] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
];
static mut swb_size_128_24: [uint8_t; 15] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
];
static mut swb_size_128_16: [uint8_t; 15] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
];
static mut swb_size_128_8: [uint8_t; 15] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
];
static mut swb_size_1024_96: [uint8_t; 41] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
    44 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
];
static mut swb_size_1024_64: [uint8_t; 47] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
];
static mut swb_size_1024_48: [uint8_t; 49] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    96 as libc::c_int as uint8_t,
];
static mut swb_size_1024_32: [uint8_t; 51] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
];
static mut swb_size_1024_24: [uint8_t; 47] = [
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    4 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    44 as libc::c_int as uint8_t,
    48 as libc::c_int as uint8_t,
    52 as libc::c_int as uint8_t,
    52 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
];
static mut swb_size_1024_16: [uint8_t; 43] = [
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    8 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    44 as libc::c_int as uint8_t,
    48 as libc::c_int as uint8_t,
    52 as libc::c_int as uint8_t,
    56 as libc::c_int as uint8_t,
    60 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
];
static mut swb_size_1024_8: [uint8_t; 40] = [
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    12 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    16 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    20 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    24 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    28 as libc::c_int as uint8_t,
    32 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
    36 as libc::c_int as uint8_t,
    40 as libc::c_int as uint8_t,
    44 as libc::c_int as uint8_t,
    48 as libc::c_int as uint8_t,
    52 as libc::c_int as uint8_t,
    56 as libc::c_int as uint8_t,
    60 as libc::c_int as uint8_t,
    64 as libc::c_int as uint8_t,
    80 as libc::c_int as uint8_t,
];

pub(crate) static mut ff_aac_swb_size_128: [*const uint8_t; 13] = unsafe {
    [
        swb_size_128_96.as_ptr(),
        swb_size_128_96.as_ptr(),
        swb_size_128_64.as_ptr(),
        swb_size_128_48.as_ptr(),
        swb_size_128_48.as_ptr(),
        swb_size_128_48.as_ptr(),
        swb_size_128_24.as_ptr(),
        swb_size_128_24.as_ptr(),
        swb_size_128_16.as_ptr(),
        swb_size_128_16.as_ptr(),
        swb_size_128_16.as_ptr(),
        swb_size_128_8.as_ptr(),
        swb_size_128_8.as_ptr(),
    ]
};

pub(crate) static mut ff_aac_swb_size_1024: [*const uint8_t; 13] = unsafe {
    [
        swb_size_1024_96.as_ptr(),
        swb_size_1024_96.as_ptr(),
        swb_size_1024_64.as_ptr(),
        swb_size_1024_48.as_ptr(),
        swb_size_1024_48.as_ptr(),
        swb_size_1024_32.as_ptr(),
        swb_size_1024_24.as_ptr(),
        swb_size_1024_24.as_ptr(),
        swb_size_1024_16.as_ptr(),
        swb_size_1024_16.as_ptr(),
        swb_size_1024_16.as_ptr(),
        swb_size_1024_8.as_ptr(),
        swb_size_1024_8.as_ptr(),
    ]
};

pub(crate) static mut ff_aac_swb_size_128_len: libc::c_int = 0;

pub(crate) static mut ff_aac_swb_size_1024_len: libc::c_int = 0;
unsafe fn run_static_initializers() {
    ff_aac_swb_size_128_len = (::core::mem::size_of::<[*const uint8_t; 13]>() as libc::c_ulong)
        .wrapping_div(::core::mem::size_of::<*const uint8_t>() as libc::c_ulong)
        as libc::c_int;
    ff_aac_swb_size_1024_len = (::core::mem::size_of::<[*const uint8_t; 13]>() as libc::c_ulong)
        .wrapping_div(::core::mem::size_of::<*const uint8_t>() as libc::c_ulong)
        as libc::c_int;
}
#[used]
#[cfg_attr(target_os = "linux", link_section = ".init_array")]
#[cfg_attr(target_os = "windows", link_section = ".CRT$XIB")]
#[cfg_attr(target_os = "macos", link_section = "__DATA,__mod_init_func")]
static INIT_ARRAY: [unsafe fn(); 1] = [run_static_initializers];
