use ffi::codec::channel::{self as ch, AVChannelLayout};
use libc::{c_int, c_uchar};

use super::{channel_layout, config_map};
use crate::types::*;

#[derive(Copy, Clone)]
#[repr(C)]
pub(crate) struct Info {
    pub(crate) layout: AVChannelLayout,
    pub(crate) num_ele: [c_int; 4],
    pub(crate) pairing: [[c_int; 8]; 3],
    pub(crate) index: [[c_int; 8]; 4],
    pub(crate) config_map: [c_uchar; 16],
    pub(crate) reorder_map: [c_uchar; 16],
}

pub(crate) const CONFIGS: [Info; 29] = [
    Info {
        layout: channel_layout(&[ch::FRONT_CENTER]),
        num_ele: [1, 0, 0, 0],
        pairing: [[0; 8], [0; 8], [0; 8]],
        index: [[0; 8], [0; 8], [0; 8], [0; 8]],
        config_map: config_map(&[TYPE_SCE]),
        reorder_map: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[ch::FRONT_LEFT, ch::FRONT_RIGHT]),
        num_ele: [1, 0, 0, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        index: [[0; 8], [0; 8], [0; 8], [0; 8]],
        config_map: config_map(&[TYPE_CPE]),
        reorder_map: [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[ch::FRONT_LEFT, ch::FRONT_RIGHT, ch::LOW_FREQUENCY]),
        num_ele: [1, 0, 0, 1],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        index: [[0; 8], [0; 8], [0; 8], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_LFE]),
        reorder_map: [0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[ch::FRONT_LEFT, ch::FRONT_RIGHT, ch::BACK_CENTER]),
        num_ele: [1, 0, 1, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        index: [[0; 8], [0; 8], [0; 8], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[ch::FRONT_LEFT, ch::FRONT_RIGHT, ch::FRONT_CENTER]),
        num_ele: [2, 0, 0, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        index: [[0; 8], [0; 8], [0; 8], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::LOW_FREQUENCY,
        ]),
        num_ele: [2, 0, 0, 1],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        index: [[0; 8], [0; 8], [0; 8], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_LFE]),
        reorder_map: [0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::BACK_CENTER,
        ]),
        num_ele: [2, 0, 1, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        index: [[0; 8], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::BACK_CENTER,
            ch::LOW_FREQUENCY,
        ]),
        num_ele: [2, 1, 1, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [2, 0, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
        ]),
        num_ele: [1, 1, 0, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8]],
        index: [[0; 8], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
        ]),
        num_ele: [1, 0, 1, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0]],
        index: [[0; 8], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
        ]),
        num_ele: [2, 1, 0, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8]],
        index: [[0; 8], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::LOW_FREQUENCY,
        ]),
        num_ele: [2, 1, 1, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
        ]),
        num_ele: [2, 0, 1, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0]],
        index: [[0; 8], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
            ch::LOW_FREQUENCY,
        ]),
        num_ele: [2, 1, 1, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::BACK_CENTER,
        ]),
        num_ele: [2, 1, 1, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::FRONT_LEFT_OF_CENTER,
            ch::FRONT_RIGHT_OF_CENTER,
        ]),
        num_ele: [2, 1, 0, 0],
        pairing: [[1, 1, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0], [0; 8]],
        index: [
            [1, 0, 0, 0, 0, 0, 0, 0],
            [2, 0, 0, 0, 0, 0, 0, 0],
            [0; 8],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_CPE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
            ch::BACK_CENTER,
        ]),
        num_ele: [2, 0, 2, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0]],
        index: [[0; 8], [0; 8], [1, 1, 0, 0, 0, 0, 0, 0], [0; 8]],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::LOW_FREQUENCY,
            ch::BACK_CENTER,
        ]),
        num_ele: [2, 1, 2, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 2, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
            ch::LOW_FREQUENCY,
            ch::BACK_CENTER,
        ]),
        num_ele: [2, 1, 2, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 2, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::FRONT_LEFT_OF_CENTER,
            ch::FRONT_RIGHT_OF_CENTER,
            ch::LOW_FREQUENCY,
        ]),
        num_ele: [2, 1, 2, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 0, 0, 0, 0, 0, 0, 0]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 2, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
        ]),
        num_ele: [2, 1, 1, 0],
        pairing: [
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
        ],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [2, 0, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::FRONT_LEFT_OF_CENTER,
            ch::FRONT_RIGHT_OF_CENTER,
        ]),
        num_ele: [2, 1, 1, 0],
        pairing: [
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
        ],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [2, 0, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::LOW_FREQUENCY,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
        ]),
        num_ele: [2, 1, 2, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 1, 0, 0, 0, 0, 0, 0]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 2, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_CPE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::LOW_FREQUENCY,
            ch::FRONT_LEFT_OF_CENTER,
            ch::FRONT_RIGHT_OF_CENTER,
        ]),
        num_ele: [2, 1, 2, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 1, 0, 0, 0, 0, 0, 0]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 2, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_CPE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
            ch::LOW_FREQUENCY,
            ch::FRONT_LEFT_OF_CENTER,
            ch::FRONT_RIGHT_OF_CENTER,
        ]),
        num_ele: [2, 1, 2, 0],
        pairing: [[1, 0, 0, 0, 0, 0, 0, 0], [0; 8], [1, 1, 0, 0, 0, 0, 0, 0]],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 2, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_SCE, TYPE_CPE, TYPE_CPE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::BACK_LEFT,
            ch::BACK_CENTER,
            ch::BACK_RIGHT,
        ]),
        num_ele: [2, 1, 2, 0],
        pairing: [
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
        ],
        index: [
            [0; 8],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [2, 1, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::BACK_LEFT,
            ch::BACK_CENTER,
            ch::BACK_RIGHT,
            ch::TOP_CENTER,
        ]),
        num_ele: [2, 2, 2, 0],
        pairing: [
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
        ],
        index: [
            [0; 8],
            [1, 1, 0, 0, 0, 0, 0, 0],
            [2, 2, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::FRONT_LEFT_OF_CENTER,
            ch::FRONT_RIGHT_OF_CENTER,
            ch::BACK_CENTER,
            ch::BACK_LEFT,
            ch::BACK_RIGHT,
            ch::TOP_CENTER,
        ]),
        num_ele: [2, 2, 2, 0],
        pairing: [
            [1, 1, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0],
        ],
        index: [
            [0, 1, 0, 0, 0, 0, 0, 0],
            [2, 0, 0, 0, 0, 0, 0, 0],
            [3, 1, 0, 0, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[TYPE_CPE, TYPE_CPE, TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_SCE]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0],
    },
    Info {
        layout: channel_layout(&[
            ch::FRONT_LEFT,
            ch::FRONT_RIGHT,
            ch::FRONT_CENTER,
            ch::SIDE_LEFT,
            ch::SIDE_RIGHT,
            ch::BACK_LEFT,
            ch::BACK_CENTER,
            ch::BACK_RIGHT,
            ch::WIDE_LEFT,
            ch::WIDE_RIGHT,
            ch::TOP_BACK_LEFT,
            ch::TOP_BACK_RIGHT,
            ch::TOP_BACK_CENTER,
            ch::TOP_FRONT_CENTER,
            ch::TOP_FRONT_LEFT,
            ch::TOP_FRONT_RIGHT,
        ]),
        num_ele: [4, 2, 4, 0],
        pairing: [
            [1, 0, 1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0, 0],
            [1, 0, 1, 0, 0, 0, 0, 0],
        ],
        index: [
            [0, 0, 1, 1, 0, 0, 0, 0],
            [2, 3, 0, 0, 0, 0, 0, 0],
            [4, 2, 5, 3, 0, 0, 0, 0],
            [0; 8],
        ],
        config_map: config_map(&[
            TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_SCE, TYPE_CPE, TYPE_CPE, TYPE_CPE, TYPE_SCE,
            TYPE_CPE, TYPE_SCE,
        ]),
        reorder_map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
];
